combat:
  archer:
    # Linear scaling from level 1 to 10.
    arrow-save-chance:
      min: 0.10
      max: 0.30
    damage-bonus:
      min: 0.10
      max: 1.00
    proc:
      lightning:
        level5: 0.20
        level10: 0.30
      debuff:
        level5: 0.20
        level10: 0.50

  tank:
    # Added directly to GENERIC_MAX_HEALTH (2 HP = 1 heart)
    health-bonus:
      base: 4.0
      per-level: 2.15
